# This is a basic workflow to help you get started with Actions

name: Plugin Publish

on:
  issue_comment:
    types: [created]
  workflow_dispatch:
    
jobs:
  issue_commented:
    name: PR comment
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up java 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 'jruby-9.2.19.0'
      - run: |
          curl https://artifacts.elastic.co/downloads/logstash/logstash-7.15.0-linux-x86_64.tar.gz -O logstash.tgz
          tar -zxf logstash.tar.gz -C logstash
      - run: |
          ls -lha
      - run: |
          LOGSTASH_SOURCE=1 LOGSTASH_PATH=/Users/joaoduarte/elastic/logstash/.bare bundle exec rake vendor
