# This is a basic workflow to help you get started with Actions

name: Plugin Publish

on:
  workflow_dispatch:

jobs:
  issue_commented:
    name: PR comment
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up java 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 'jruby-9.2.19.0'
      - run: |
          wget https://raw.githubusercontent.com/jsvd/test-action/test/action.rb
          ruby action.rb
      - run: |
          curl https://artifacts.elastic.co/downloads/logstash/logstash-7.15.0-linux-x86_64.tar.gz -o logstash.tar.gz
          tar -zxf logstash.tar.gz
      - env:
          LOGSTASH_SOURCE: 1
          LOGSTASH_PATH: /home/runner/work/test-repo/test-repo/logstash-7.15.0
        run: bundle install
      - env:
          LOGSTASH_SOURCE: 1
          LOGSTASH_PATH: /home/runner/work/test-repo/test-repo/logstash-7.15.0
        run: bundle exec rake vendor
      - name: Publish gem and tag the git repository
        env:
          LOGSTASH_SOURCE: 1
          LOGSTASH_PATH: /home/runner/work/test-repo/test-repo/logstash-7.15.0
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: bundle exec rake publish_gem
