# This is a basic workflow to help you get started with Actions

name: Plugin Publish

on:
  issue_comment:
    types: [created]
  workflow_dispatch:
    
jobs:
  issue_commented:
    name: PR comment
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up java 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - run: |
        curl https://repo1.maven.org/maven2/org/jruby/jruby-dist/9.2.19.0/jruby-dist-9.2.19.0-bin.tar.gz | tar -zxf
      - uses: jsvd/test-action@test
