name: Backport PR to another branch
on:
  issue_comment:
    types: [created]

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: |
      (github.event.issue.pull_request && startsWith(github.event.comment.body, '@logstashmachine backport')) &&
      (github.actor == 'jsvd' || github.actor == 'meh')
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - env:
          BODY: ${{ github.event.comment.body }}
        run: |
          echo "branch=$(echo "$BODY" | cut -d " " -f 3)" >> $GITHUB_ENV
      - run: |
          mkdir ~/.elastic && echo ${{ github.token }} >> ~/.elastic/github.token
      - name: execute py script # run the run.py to get the latest data
        run: pip install requests
      - name: execute py script # run the run.py to get the latest data
        run: python devtools/backport ${{ env.branch }} ${{ github.event.issue.number }} --remote=origin --yes
