name: Backport PR to another branch
on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  contents: read

jobs:
  pr_commented:
    name: PR comment
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.comment.body }}
          regex: '^@logstashmachine backport (main|[0-9\.]+)$'
      - if: ${{ steps.regex-match.outputs.group1 == '' }}
        run: exit 1
      - uses: tspascoal/get-user-teams-membership@v1
        with: 
          username: ${{ github.actor }}
          organization: elastic
          team: logstash
          GITHUB_TOKEN: ${{ secrets.READ_ORG_SECRET_JSVD }}
      - if: ${{ steps.checkUserMember.outputs.isTeamMember == 'false' }}
        run: exit 1
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: |
          mkdir ~/.elastic && echo ${{ github.token }} >> ~/.elastic/github.token
      - run: pip install requests
      - name: run backport
        run: python devtools/backport ${{ steps.regex-match.outputs.group1 }} ${{ github.event.issue.number }} --remote=origin --yes
